---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: write
    image: alpine
    volumes:
      - name: cache
        path: /mnt/cache
    environment:
      SUPERSECRET:
        from_secret: supersecret
    commands:
      - echo $SUPERSECRET > /mnt/cache/secret
  - name: read
    image: alpine
    volumes:
      - name: cache
        path: /mnt/cache
    commands:
      - cat /mnt/cache/secret
volumes:
  - name: cache
    temp: {}
